### PR TITLE
Fixes #1640 - Prevent loading skeletons from being dismissed too soon…

### LINKED ISSUE #1640: Loading skeleton in the room list doesn't work properly
### Steps to reproduce

1. Login fresh
2. Observe the loading skeleton in the room list
3. The loading skeleton goes away before the content is ready

https://github.com/vector-im/element-x-ios/assets/19324622/3c278444-4757-4855-b5dc-84cae7832f25

#### What did you expect?
The skeleton goes away **after** the content is ready

#### What happened instead?
The skeleton disappeared **before** the content was ready

### Your phone model

iPhone 14 simulator

### Operating system version

_No response_

### Application version

Commit fef3077f95b6e77f6e985fcb252c5160dd7fe760

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by stefanceriu**
…. Avoid weird animations caused by the session verification banner.

### CODE REVIEW

File: ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift [hunk 1]
```diff
@@ -148,7 +148,9 @@ class HomeScreenViewModel: HomeScreenViewModelType, HomeScreenViewModelProtocol
             .sink { [weak self] state, rooms in
                 guard let self else { return }
                 
-                let isLoadingData = !state.isLoaded && rooms.isEmpty
+                // Rust sends back loaded even when no rooms are loaded yet, check room for empty to be sure
+                let isLoadingData = !state.isLoaded || rooms.isEmpty
```
Comment (pixlwave) [inline ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift:152]: This won't work, it will prevent `hasNoRooms` from being used to show the empty state. Does it work for this case in combination with `state.totalNumberOfRooms == 0`?

Comment (stefanceriu) [reply ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift:152]: Bah, of course 🤦 Might work, let me try it out

Comment (stefanceriu) [reply ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift:152]: Yep, that seems fine

Screenshot 2023-09-13 at 08 33 41

**Review by pixlwave — APPROVED** [review]
LGTM 👍

File: ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift (hunk 1 above)
Comment (pixlwave) [reply ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift]: Nice, thanks.
