### PR TITLE
Fixes #617 - Prevent navigation bar breaking when backgrounding the a…

### LINKED ISSUE #617: Backgrounding the app in iPad split view or slide over breaks navigation.
### Steps to reproduce

1. Open the app in split view (½ or ¼ width) or slide over on an iPad.
2. Tap a room to push it into view.
3. Background the app.
4. Foreground the app.

#### What did you expect?
The navigation bar to show the room name, avatar and a back button.

#### What happened instead?
The navigation bar now shows your user avatar and the title All Chats.

https://user-images.githubusercontent.com/6060466/220904043-168dbfdd-e126-48e8-a99e-7239ed03707a.mp4

### Your phone model

iPad (any)

### Operating system version

iOS 16.3.1

### Application version

Nightly 1.0.21 (136)

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by stefanceriu**
…pp froma a split view

### CODE REVIEW

File: ElementX/Sources/Application/Navigation/NavigationCoordinators.swift [hunk 1]
```diff
@@ -380,6 +384,13 @@ private struct NavigationSplitCoordinatorView: View {
         .fullScreenCover(item: $navigationSplitCoordinator.fullScreenCoverModule) { module in
             module.coordinator?.toPresentable()
         }
+        .onChange(of: horizontalSizeClass) { value in
+            guard scenePhase != .background else {
```
Comment (pixlwave) [inline ElementX/Sources/Application/Navigation/NavigationCoordinators.swift:388]: Have you tested this when creating a split in the multi-tasking switcher. Specifically I'm thinking
- Open EX.
- Go back to the home screen.
- Open Safari.
- Bring up the app switcher.
- Drag the EX window (not icon) on top of Safari to create a split.
- Open the split.

Comment (stefanceriu) [reply ElementX/Sources/Application/Navigation/NavigationCoordinators.swift:388]: That does indeed break it, good catch. Fixed it by adding moar code, obviously 😅

**Review by pixlwave — APPROVED** [review]
