### PR TITLE
Fix NSE Leak

### LINKED ISSUE #1923: Missing notifications because of a memory leak in NSE
### Steps to reproduce

- Do not open the app
- Received10 messages that should trigger a notification for each
- Count notifications you receive

#### What did you expect?
I should get 10 notifications

#### What happened instead?
Sometimes I get only 2

### Your phone model

_No response_

### Operating system version

_No response_

### Application version

_No response_

### Homeserver

_No response_

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by Velin92**
WIP: Requires updated SDK

fixes #1923

### CODE REVIEW

File: NSE/Sources/NotificationServiceExtension.swift [hunk 1]
```diff
@@ -18,15 +18,38 @@ import Intents
...
+//      notifications it needs to
+//  4)  Extension notifies its work is complete by calling
+//      the contentHandler
+//  5)  If the extension takes too long to perform its work
+//      (more than 30s), it will be notified and immediately
+//      terminated
+//
+// Note that the NSE does *not* always spawn a new process to
+// handle a new notification and will also try and process notifications
+// in parallel. `didReceive` could be called twice for the same process,
```
Comment (pixlwave) [inline NSE/Sources/NotificationServiceExtension.swift:35]: Are you sure about in parallel? I thought it always queued the next one up until the contentHandler is called 🤔

Otherwise you could receive notifications out of order, no?

File: ElementX/Sources/Services/Media/Provider/MediaFileHandleProxy.swift
Comment (pixlwave) [inline ElementX/Sources/Services/Media/Provider/MediaFileHandleProxy.swift:1]: What's are these two changes about??

**Review by pixlwave — APPROVED** [review]
Nice 👌

File: NSE/Sources/NotificationServiceExtension.swift (hunk 1 above)
Comment (Velin92) [reply NSE/Sources/NotificationServiceExtension.swift:35]: I think the parallel is referring to the parallel threads that can handle the didReceive function, but is still possible that the different threads still serve only one notification per run during the lifecycle of the didReceive function making the other threads wait the first one that has come. But not 100% sure

File: ElementX/Sources/Services/Media/Provider/MediaFileHandleProxy.swift
Comment (Velin92) [reply ElementX/Sources/Services/Media/Provider/MediaFileHandleProxy.swift:1]: the protocol now requires to be using a AnyObject.
