### PR TITLE
Make the attachment menu an actual menu.

### LINKED ISSUE #2157: Composer menue items have the wrong color when using dark mode
### Steps to reproduce

1. What can you see?
I see nothing ;)

3. What do you click?
Open the app -> go to a room -> prepare to write a message by tapping in the composer -> tap the "plus" icon

#### What did you expect?
See the menue.
IMG_1602FEF565A5-1

#### What happened instead?
Headache :)

### Your phone model

_No response_

### Operating system version

_No response_

### Application version

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by pixlwave**
A second attempt, fixes #2157, the root cause for which remains a mystery to us (we know that removing the frame reader and detents fixes it, but that isn't a desirable layout). Instead, this PR replaces the popover/sheet with the native menu component which does the right thing. (Discussed with @amshakal before making the change).

https://github.com/vector-im/element-x-ios/assets/6060466/f91596d9-e172-4071-abfd-29661ba8d69a

| Light mode |
| - |
| Simulator Screenshot - iPhone 14 - 2023-12-04 at 17 36 11 |

### CODE REVIEW

File: ElementX/Sources/Screens/ComposerToolbar/ComposerToolbarModels.swift [hunk 1]
```diff
@@ -32,11 +32,7 @@ enum ComposerToolbarVoiceMessageAction {
 
 enum ComposerToolbarViewModelAction {
     case sendMessage(plain: String, html: String?, mode: RoomScreenComposerMode, intentionalMentions: IntentionalMentions)
-    case displayCameraPicker
-    case displayMediaPicker
-    case displayDocumentPicker
-    case displayLocationPicker
-    case displayNewPollForm
+    case attach(ComposerAttachmentType)
```
Comment (stefanceriu) [inline ElementX/Sources/Screens/ComposerToolbar/ComposerToolbarModels.swift:35]: Borat Small

**Review by stefanceriu — APPROVED** [review]
Looks good to me! 👍
