### PR TITLE
Auto dismiss bug report when completed

### LINKED ISSUE #76: Bug report screen should disappear after sending
It feels weird to stay on this screen after upload. It looks like there is a sending issue.

### PR DESCRIPTION
**Pull request by ismailgulek**
Fixes #76

### CODE REVIEW

File: ElementX/Sources/Screens/Settings/SettingsCoordinator.swift [hunk 1]
```diff
@@ -106,4 +108,9 @@ final class SettingsCoordinator: Coordinator, Presentable {
             self.remove(childCoordinator: coordinator)
         }
     }
+
+    /// Show success indicator
+    private func showSuccess(label: String) {
+        errorIndicator = indicatorPresenter.present(.success(label: label))
```
Comment (pixlwave) [inline ElementX/Sources/Screens/Settings/SettingsCoordinator.swift:114]: I think I commented on one of these before how it seems weird to me to have an `errorIndicator` that shows `success`. Maybe it would make more sense to call this the `statusIndicator`?

**Review by pixlwave — APPROVED** [review]
LGTM 👍

File: ElementX/Sources/Screens/Settings/SettingsCoordinator.swift (hunk 1 above)
Comment (ismailgulek) [reply ElementX/Sources/Screens/Settings/SettingsCoordinator.swift]: Makes perfect sense, updated throughout the app.
