### PR TITLE
Fixes #954 - Implement media upload cancelling

### LINKED ISSUE #954: There is no way to cancel an image upload
### Steps to reproduce

1. Upload an image on bad connectivity
2. Observe spurious Loading spinner (which should surely be Sending)
3. Hit cancel
4. nothing happens

#### What did you expect?
 cancel button should work
#### What happened instead?
it doesn’t

### Your phone model

_No response_

### Operating system version

_No response_

### Application version

223

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by stefanceriu**
Requires new SDK release

### CODE REVIEW

File: ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenViewModel.swift [hunk 1]
```diff
@@ -67,22 +73,28 @@ class MediaUploadPreviewScreenViewModel: MediaUploadPreviewScreenViewModelType,
...
+            requestHandle?.cancel()
             callback?(.dismiss)
         }
     }
     
     // MARK: - Private
     
     private func sendAttachment(mediaInfo: MediaInfo, progressSubject: CurrentValueSubject<Double, Never>) async -> Result<Void, RoomProxyError> {
+        let requestHandle: ((SendAttachmentJoinHandleProtocol) -> Void) = { [weak self] handle in
+            self?.requestHandle?.cancel()
```
Comment (pixlwave) [inline ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenViewModel.swift:85]: Why does it call cancel when storing the handle?

**Review by pixlwave — APPROVED** [review]

File: ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenViewModel.swift (hunk 1 above)
Comment (stefanceriu) [reply ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenViewModel.swift:85]: Just in case there was another one already set ¯\_(ツ)_/¯
