### PR TITLE
Tweaks for macOS

### LINKED ISSUE #1280: Compose button is moving around the screen on macOS
### Steps to reproduce

1. Open the Element X on macOS
2. Look at the compose button

#### What did you expect?

The compose button to stay still.

#### What happened instead?

The compose button was moving around.

### Your phone model

_No response_

### Operating system version

13.4.1 (22F82)

### Application version

1.1.8 (54)

### Homeserver

matrix.org

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by pixlwave**
This PR makes 3 tweaks the use on macOS:
- Fixes #1280.
- Allows right-clicking on timeline items again by reusing the timeline menu actions to compute a context menu when on macOS. This is a more expected gesture on macOS, but long clicking is still available for those who want that.
- Uses an inline preview when uploading a media file as the floating QuickLook panel was obscuring the cancel/send buttons which was confusing
    - This change has one caveat: as noted in the [docs](https://developer.apple.com/documentation/quicklook/qlpreviewcontroller#3668757), previews are no longer interactive on Mac, so you can't play a video, zoom into an image or scroll through a document. The limitation seems worthwhile to me given that you can actually see the send button though.

**Context Menu**
Context

https://github.com/vector-im/element-x-ios/assets/6060466/1367a10c-b870-42e9-8b62-cf0a8ed48f7e

### CODE REVIEW

File: ElementX/Sources/Screens/MediaUploadPreviewScreen/View/MediaUploadPreviewScreen.swift [hunk 1]
```diff
@@ -20,13 +20,19 @@ import SwiftUI
...
     var body: some View {
         PreviewView(context: context,
                     fileURL: context.viewState.url,
                     title: context.viewState.title)
             .id(UUID())
+            .navigationTitle(title)
+            .navigationBarTitleDisplayMode(.inline)
             .disabled(context.viewState.shouldDisableInteraction)
-            .ignoresSafeArea(edges: .bottom)
+            .ignoresSafeArea(edges: [.horizontal, .bottom])
```
Comment (pixlwave) [inline ElementX/Sources/Screens/MediaUploadPreviewScreen/View/MediaUploadPreviewScreen.swift:35]: This is the only change that affects iPadOS/iOS - iPhone in landscape would put white bars either side of the preview when you go fullscreen, which this fixes.

File: ElementX/Sources/Screens/RoomScreen/View/TimelineItemMenu.swift [hunk 2]
```diff
@@ -79,20 +83,37 @@ enum TimelineItemMenuAction: Identifiable, Hashable {
...
+        case .copy: return Label(L10n.actionCopy, systemImage: "doc.on.doc")
+        case .edit: return Label(L10n.actionEdit, systemImage: "pencil.line")
+        case .copyPermalink: return Label(L10n.actionCopyLinkToMessage, systemImage: "link")
+        case .reply: return Label(L10n.actionReply, systemImage: "arrowshape.turn.up.left")
+        case .forward: return Label(L10n.actionForward, systemImage: "arrowshape.turn.up.right")
+        case .redact: return Label(L10n.actionRemove, systemImage: "trash")
+        case .viewSource: return Label(L10n.actionViewSource, systemImage: "doc.text.below.ecg")
+        case .retryDecryption: return Label(L10n.actionRetryDecryption, systemImage: "arrow.down.message")
+        case .report: return Label(L10n.actionReportContent, systemImage: "exclamationmark.bubble")
+        case .react: return Label(L10n.screenRoomTimelineAddReaction, systemImage: "hand.thumbsup")
```
Comment (pixlwave) [inline ElementX/Sources/Screens/RoomScreen/View/TimelineItemMenu.swift:99]: Not sure if either of these are correct, the image isn't shown anyway but the title is "Add emoji" 🤔

File: ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift [hunk 3]
```diff
@@ -95,11 +95,37 @@ struct RoomScreenViewState: BindableState {
...
     
+    /// A closure providing the actions to show when long pressing on an item in the timeline.
     var timelineItemMenuActionProvider: (@MainActor (_ itemId: TimelineItemIdentifier) -> TimelineItemMenuActions?)?
     
-    var composerMode: RoomScreenComposerMode = .default
+    /// Builds the contents of the context menu shown when right clicking an item in the timeline on a Mac.
+    @MainActor @ViewBuilder
+    func macContextMenu(item: RoomTimelineItemProtocol, send: @escaping (TimelineItemMenuAction) -> Void) -> some View {
+        if ProcessInfo.processInfo.isiOSAppOnMac {
+            if let menu = timelineItemMenuActionProvider?(item.id) {
```
Comment (stefanceriu) [inline ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift:110]: This isn't techincally a menu, just a list of actions

File: ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift [hunk 4]
```diff
@@ -95,11 +95,37 @@ struct RoomScreenViewState: BindableState {
...
+    
     var bindings: RoomScreenViewStateBindings
     
+    /// A closure providing the actions to show when long pressing on an item in the timeline.
     var timelineItemMenuActionProvider: (@MainActor (_ itemId: TimelineItemIdentifier) -> TimelineItemMenuActions?)?
     
-    var composerMode: RoomScreenComposerMode = .default
+    /// Builds the contents of the context menu shown when right clicking an item in the timeline on a Mac.
+    @MainActor @ViewBuilder
+    func macContextMenu(item: RoomTimelineItemProtocol, send: @escaping (TimelineItemMenuAction) -> Void) -> some View {
```
Comment (stefanceriu) [inline ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift:108]: Are you sure this View belongs here? I would've expected it to be to be within a separate file withing the View subfolder

**Review by stefanceriu — APPROVED** [review]
Very nice, one step closer to using this as a desktop daily driver 🙌

File: ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift (hunk 4 above)
Comment (pixlwave) [reply ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift:108]: Fair, I wasn't really sure where to put it and was trying to use it in a similar was to the action provider, but I'll split it out 👍

File: ElementX/Sources/Screens/RoomScreen/View/TimelineItemMenu.swift (hunk 2 above)
Comment (pixlwave) [reply ElementX/Sources/Screens/RoomScreen/View/TimelineItemMenu.swift]: Updated to `React` after feedback from Design.
